#############################################################################
# Makefile for building: target/PrimeNumberGame
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  PrimeNumberGame.pro
# Template: app
# Command: /opt/Qt/5.3/gcc_64/bin/qmake -o Makefile PrimeNumberGame.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/opt/Qt/5.3/gcc_64/mkspecs/linux-g++ -I. -I. -Isrc -Isrc/util -Isrc/object -Isrc/event -Isrc/force -I/opt/Qt/5.3/gcc_64/include -I/opt/Qt/5.3/gcc_64/include/QtOpenGL -I/opt/Qt/5.3/gcc_64/include/QtWidgets -I/opt/Qt/5.3/gcc_64/include/QtGui -I/opt/Qt/5.3/gcc_64/include/QtCore -Igenerated
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/Qt/5.3/gcc_64 -Wl,-rpath,/opt/Qt/5.3/gcc_64/lib
LIBS          = $(SUBLIBS) -lGLU -L/opt/Qt/5.3/gcc_64/lib -lQt5OpenGL -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/Qt/5.3/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = generated/

####### Files

SOURCES       = src/CrashKeeper.cpp \
		src/CrashResult.cpp \
		src/Field.cpp \
		src/main.cpp \
		src/Sight.cpp \
		src/event/CrashEvent.cpp \
		src/event/Event.cpp \
		src/event/ForceEvent.cpp \
		src/event/MoveEvent.cpp \
		src/event/SightMoveEvent.cpp \
		src/force/Force.cpp \
		src/force/Gravity.cpp \
		src/force/Impulse.cpp \
		src/force/StickForce.cpp \
		src/object/Gunner.cpp \
		src/object/NumberBox.cpp \
		src/object/Object.cpp \
		src/object/ObjectStatus.cpp \
		src/object/Player.cpp \
		src/util/Calculater.cpp \
		src/util/Vector.cpp generated/moc_Field.cpp \
		generated/moc_Sight.cpp
OBJECTS       = generated/CrashKeeper.o \
		generated/CrashResult.o \
		generated/Field.o \
		generated/main.o \
		generated/Sight.o \
		generated/CrashEvent.o \
		generated/Event.o \
		generated/ForceEvent.o \
		generated/MoveEvent.o \
		generated/SightMoveEvent.o \
		generated/Force.o \
		generated/Gravity.o \
		generated/Impulse.o \
		generated/StickForce.o \
		generated/Gunner.o \
		generated/NumberBox.o \
		generated/Object.o \
		generated/ObjectStatus.o \
		generated/Player.o \
		generated/Calculater.o \
		generated/Vector.o \
		generated/moc_Field.o \
		generated/moc_Sight.o
DIST          = /opt/Qt/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/spec_post.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/uic.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/lex.prf \
		PrimeNumberGame.pro src/CrashKeeper.cpp \
		src/CrashResult.cpp \
		src/Field.cpp \
		src/main.cpp \
		src/Sight.cpp \
		src/event/CrashEvent.cpp \
		src/event/Event.cpp \
		src/event/ForceEvent.cpp \
		src/event/MoveEvent.cpp \
		src/event/SightMoveEvent.cpp \
		src/force/Force.cpp \
		src/force/Gravity.cpp \
		src/force/Impulse.cpp \
		src/force/StickForce.cpp \
		src/object/Gunner.cpp \
		src/object/NumberBox.cpp \
		src/object/Object.cpp \
		src/object/ObjectStatus.cpp \
		src/object/Player.cpp \
		src/util/Calculater.cpp \
		src/util/Vector.cpp
QMAKE_TARGET  = PrimeNumberGame
DESTDIR       = target/#avoid trailing-slash linebreak
TARGET        = target/PrimeNumberGame


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@test -d target/ || mkdir -p target/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: PrimeNumberGame.pro /opt/Qt/5.3/gcc_64/mkspecs/linux-g++/qmake.conf /opt/Qt/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/spec_post.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/uic.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/lex.prf \
		PrimeNumberGame.pro \
		/opt/Qt/5.3/gcc_64/lib/libQt5OpenGL.prl \
		/opt/Qt/5.3/gcc_64/lib/libQt5Widgets.prl \
		/opt/Qt/5.3/gcc_64/lib/libQt5Gui.prl \
		/opt/Qt/5.3/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile PrimeNumberGame.pro
/opt/Qt/5.3/gcc_64/mkspecs/features/spec_pre.prf:
/opt/Qt/5.3/gcc_64/mkspecs/common/shell-unix.conf:
/opt/Qt/5.3/gcc_64/mkspecs/common/unix.conf:
/opt/Qt/5.3/gcc_64/mkspecs/common/linux.conf:
/opt/Qt/5.3/gcc_64/mkspecs/common/gcc-base.conf:
/opt/Qt/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf:
/opt/Qt/5.3/gcc_64/mkspecs/common/g++-base.conf:
/opt/Qt/5.3/gcc_64/mkspecs/common/g++-unix.conf:
/opt/Qt/5.3/gcc_64/mkspecs/qconfig.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/features/qt_functions.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/qt_config.prf:
/opt/Qt/5.3/gcc_64/mkspecs/linux-g++/qmake.conf:
/opt/Qt/5.3/gcc_64/mkspecs/features/spec_post.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/exclusive_builds.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/default_pre.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/resolve_config.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/default_post.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/warn_on.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/qt.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/resources.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/moc.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/unix/opengl.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/uic.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/unix/thread.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/testcase_targets.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/exceptions.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/yacc.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/lex.prf:
PrimeNumberGame.pro:
/opt/Qt/5.3/gcc_64/lib/libQt5OpenGL.prl:
/opt/Qt/5.3/gcc_64/lib/libQt5Widgets.prl:
/opt/Qt/5.3/gcc_64/lib/libQt5Gui.prl:
/opt/Qt/5.3/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile PrimeNumberGame.pro

qmake_all: FORCE

dist: 
	@test -d generated/PrimeNumberGame1.0.0 || mkdir -p generated/PrimeNumberGame1.0.0
	$(COPY_FILE) --parents $(DIST) generated/PrimeNumberGame1.0.0/ && $(COPY_FILE) --parents src/CrashKeeper.h src/CrashResult.h src/Field.h src/Sight.h src/event/CrashEvent.h src/event/Event.h src/event/ForceEvent.h src/event/MoveEvent.h src/event/SightMoveEvent.h src/force/Force.h src/force/Gravity.h src/force/Impulse.h src/force/StickForce.h src/object/Gunner.h src/object/NumberBox.h src/object/Object.h src/object/ObjectStatus.h src/object/Player.h src/util/Array.h src/util/Calculater.h src/util/Define.h src/util/Pair.h src/util/Vector.h generated/PrimeNumberGame1.0.0/ && $(COPY_FILE) --parents src/CrashKeeper.cpp src/CrashResult.cpp src/Field.cpp src/main.cpp src/Sight.cpp src/event/CrashEvent.cpp src/event/Event.cpp src/event/ForceEvent.cpp src/event/MoveEvent.cpp src/event/SightMoveEvent.cpp src/force/Force.cpp src/force/Gravity.cpp src/force/Impulse.cpp src/force/StickForce.cpp src/object/Gunner.cpp src/object/NumberBox.cpp src/object/Object.cpp src/object/ObjectStatus.cpp src/object/Player.cpp src/util/Calculater.cpp src/util/Vector.cpp generated/PrimeNumberGame1.0.0/ && (cd `dirname generated/PrimeNumberGame1.0.0` && $(TAR) PrimeNumberGame1.0.0.tar PrimeNumberGame1.0.0 && $(COMPRESS) PrimeNumberGame1.0.0.tar) && $(MOVE) `dirname generated/PrimeNumberGame1.0.0`/PrimeNumberGame1.0.0.tar.gz . && $(DEL_FILE) -r generated/PrimeNumberGame1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) target/$(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: generated/moc_Field.cpp generated/moc_Sight.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) generated/moc_Field.cpp generated/moc_Sight.cpp
generated/moc_Field.cpp: /opt/Qt/5.3/gcc_64/include/QtCore/QObject \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobject.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qflags.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstring.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qchar.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qlist.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobject_impl.h \
		src/util/Array.h \
		src/util/Define.h \
		src/Field.h
	/opt/Qt/5.3/gcc_64/bin/moc $(DEFINES) -I/opt/Qt/5.3/gcc_64/mkspecs/linux-g++ -I/home/sanada/Documents/program/git/PrimeNumberGame -I/home/sanada/Documents/program/git/PrimeNumberGame -I/home/sanada/Documents/program/git/PrimeNumberGame/src -I/home/sanada/Documents/program/git/PrimeNumberGame/src/util -I/home/sanada/Documents/program/git/PrimeNumberGame/src/object -I/home/sanada/Documents/program/git/PrimeNumberGame/src/event -I/home/sanada/Documents/program/git/PrimeNumberGame/src/force -I/opt/Qt/5.3/gcc_64/include -I/opt/Qt/5.3/gcc_64/include/QtOpenGL -I/opt/Qt/5.3/gcc_64/include/QtWidgets -I/opt/Qt/5.3/gcc_64/include/QtGui -I/opt/Qt/5.3/gcc_64/include/QtCore src/Field.h -o generated/moc_Field.cpp

generated/moc_Sight.cpp: /opt/Qt/5.3/gcc_64/include/QtOpenGL/QGLWidget \
		/opt/Qt/5.3/gcc_64/include/QtOpenGL/qgl.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qopengl.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qflags.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qt_windows.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qopengles2ext.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qopenglext.h \
		/opt/Qt/5.3/gcc_64/include/QtWidgets/qwidget.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobject.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstring.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qchar.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qlist.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qrect.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsize.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpalette.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qpair.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qvector.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qregion.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qline.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qimage.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qhash.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qfont.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt/5.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qkeysequence.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qevent.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmap.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qset.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qurl.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qfile.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpaintengine.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpainter.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qtextoption.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpen.h \
		/opt/Qt/5.3/gcc_64/include/QtOpenGL/qglcolormap.h \
		/opt/Qt/5.3/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/QSurfaceFormat \
		/opt/Qt/5.3/gcc_64/include/QtGui/qsurfaceformat.h \
		src/util/Vector.h \
		src/util/Array.h \
		src/util/Define.h \
		src/Sight.h
	/opt/Qt/5.3/gcc_64/bin/moc $(DEFINES) -I/opt/Qt/5.3/gcc_64/mkspecs/linux-g++ -I/home/sanada/Documents/program/git/PrimeNumberGame -I/home/sanada/Documents/program/git/PrimeNumberGame -I/home/sanada/Documents/program/git/PrimeNumberGame/src -I/home/sanada/Documents/program/git/PrimeNumberGame/src/util -I/home/sanada/Documents/program/git/PrimeNumberGame/src/object -I/home/sanada/Documents/program/git/PrimeNumberGame/src/event -I/home/sanada/Documents/program/git/PrimeNumberGame/src/force -I/opt/Qt/5.3/gcc_64/include -I/opt/Qt/5.3/gcc_64/include/QtOpenGL -I/opt/Qt/5.3/gcc_64/include/QtWidgets -I/opt/Qt/5.3/gcc_64/include/QtGui -I/opt/Qt/5.3/gcc_64/include/QtCore src/Sight.h -o generated/moc_Sight.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

generated/CrashKeeper.o: src/CrashKeeper.cpp src/CrashKeeper.h \
		src/util/Array.h \
		src/util/Define.h \
		src/util/Pair.h \
		src/object/Object.h \
		src/util/Vector.h \
		src/object/ObjectStatus.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/CrashKeeper.o src/CrashKeeper.cpp

generated/CrashResult.o: src/CrashResult.cpp src/CrashResult.h \
		src/event/CrashEvent.h \
		src/event/Event.h \
		src/Field.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/QObject \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobject.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qflags.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstring.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qchar.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qlist.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobject_impl.h \
		src/util/Array.h \
		src/util/Define.h \
		src/util/Vector.h \
		src/object/Object.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/CrashResult.o src/CrashResult.cpp

generated/Field.o: src/Field.cpp src/Field.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/QObject \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobject.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qflags.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstring.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qchar.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qlist.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobject_impl.h \
		src/util/Array.h \
		src/util/Define.h \
		src/Sight.h \
		/opt/Qt/5.3/gcc_64/include/QtOpenGL/QGLWidget \
		/opt/Qt/5.3/gcc_64/include/QtOpenGL/qgl.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qopengl.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qt_windows.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qopengles2ext.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qopenglext.h \
		/opt/Qt/5.3/gcc_64/include/QtWidgets/qwidget.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qrect.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsize.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpalette.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qpair.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qvector.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qregion.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qline.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qimage.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qhash.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qfont.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt/5.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qkeysequence.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qevent.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmap.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qset.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qurl.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qfile.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpaintengine.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpainter.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qtextoption.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpen.h \
		/opt/Qt/5.3/gcc_64/include/QtOpenGL/qglcolormap.h \
		/opt/Qt/5.3/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/QSurfaceFormat \
		/opt/Qt/5.3/gcc_64/include/QtGui/qsurfaceformat.h \
		src/util/Vector.h \
		src/force/Force.h \
		src/force/Impulse.h \
		src/force/Gravity.h \
		src/object/Object.h \
		src/object/Player.h \
		src/object/NumberBox.h \
		src/object/Gunner.h \
		src/event/MoveEvent.h \
		src/event/Event.h \
		src/event/SightMoveEvent.h \
		src/event/CrashEvent.h \
		src/event/ForceEvent.h \
		src/CrashKeeper.h \
		src/util/Pair.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/QTimer \
		/opt/Qt/5.3/gcc_64/include/QtCore/qtimer.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qbasictimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/Field.o src/Field.cpp

generated/main.o: src/main.cpp /opt/Qt/5.3/gcc_64/include/QtWidgets/QApplication \
		/opt/Qt/5.3/gcc_64/include/QtWidgets/qapplication.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qflags.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstring.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qchar.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobject.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qlist.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qeventloop.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsize.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt/5.3/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/opt/Qt/5.3/gcc_64/include/QtWidgets/qwidget.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qrect.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpalette.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qpair.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qvector.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qregion.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qline.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qimage.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qhash.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qfont.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt/5.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qkeysequence.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qevent.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmap.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qset.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qurl.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qfile.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qguiapplication.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qinputmethod.h \
		src/Field.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/QObject \
		src/util/Array.h \
		src/util/Define.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/main.o src/main.cpp

generated/Sight.o: src/Sight.cpp src/Sight.h \
		/opt/Qt/5.3/gcc_64/include/QtOpenGL/QGLWidget \
		/opt/Qt/5.3/gcc_64/include/QtOpenGL/qgl.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qopengl.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qflags.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qt_windows.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qopengles2ext.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qopenglext.h \
		/opt/Qt/5.3/gcc_64/include/QtWidgets/qwidget.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobject.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstring.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qchar.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qlist.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qrect.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsize.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpalette.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qpair.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qvector.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qregion.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qline.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qimage.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qhash.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qfont.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt/5.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qkeysequence.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qevent.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmap.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qset.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qurl.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qfile.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpaintengine.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpainter.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qtextoption.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpen.h \
		/opt/Qt/5.3/gcc_64/include/QtOpenGL/qglcolormap.h \
		/opt/Qt/5.3/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/QSurfaceFormat \
		/opt/Qt/5.3/gcc_64/include/QtGui/qsurfaceformat.h \
		src/util/Vector.h \
		src/util/Array.h \
		src/util/Define.h \
		src/object/Object.h \
		src/object/Gunner.h \
		src/object/Player.h \
		src/util/Calculater.h \
		src/force/Force.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/QKeyEvent
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/Sight.o src/Sight.cpp

generated/CrashEvent.o: src/event/CrashEvent.cpp src/event/CrashEvent.h \
		src/event/Event.h \
		src/Field.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/QObject \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobject.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qflags.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstring.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qchar.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qlist.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobject_impl.h \
		src/util/Array.h \
		src/util/Define.h \
		src/object/Object.h \
		src/util/Vector.h \
		src/force/Force.h \
		src/force/Impulse.h \
		src/force/StickForce.h \
		src/CrashResult.h \
		src/object/NumberBox.h \
		src/util/Calculater.h \
		src/CrashKeeper.h \
		src/util/Pair.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/CrashEvent.o src/event/CrashEvent.cpp

generated/Event.o: src/event/Event.cpp src/event/Event.h \
		src/Field.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/QObject \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobject.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qflags.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstring.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qchar.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qlist.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobject_impl.h \
		src/util/Array.h \
		src/util/Define.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/Event.o src/event/Event.cpp

generated/ForceEvent.o: src/event/ForceEvent.cpp src/event/ForceEvent.h \
		src/event/Event.h \
		src/Field.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/QObject \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobject.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qflags.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstring.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qchar.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qlist.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobject_impl.h \
		src/util/Array.h \
		src/util/Define.h \
		src/force/Force.h \
		src/util/Vector.h \
		src/force/Impulse.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/ForceEvent.o src/event/ForceEvent.cpp

generated/MoveEvent.o: src/event/MoveEvent.cpp src/event/MoveEvent.h \
		src/event/Event.h \
		src/Field.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/QObject \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobject.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qflags.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstring.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qchar.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qlist.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobject_impl.h \
		src/util/Array.h \
		src/util/Define.h \
		src/Sight.h \
		/opt/Qt/5.3/gcc_64/include/QtOpenGL/QGLWidget \
		/opt/Qt/5.3/gcc_64/include/QtOpenGL/qgl.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qopengl.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qt_windows.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qopengles2ext.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qopenglext.h \
		/opt/Qt/5.3/gcc_64/include/QtWidgets/qwidget.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qrect.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsize.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpalette.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qpair.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qvector.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qregion.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qline.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qimage.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qhash.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qfont.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt/5.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qkeysequence.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qevent.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmap.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qset.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qurl.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qfile.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpaintengine.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpainter.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qtextoption.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpen.h \
		/opt/Qt/5.3/gcc_64/include/QtOpenGL/qglcolormap.h \
		/opt/Qt/5.3/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/QSurfaceFormat \
		/opt/Qt/5.3/gcc_64/include/QtGui/qsurfaceformat.h \
		src/util/Vector.h \
		src/object/Object.h \
		src/object/ObjectStatus.h \
		src/object/Player.h \
		src/object/Gunner.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/MoveEvent.o src/event/MoveEvent.cpp

generated/SightMoveEvent.o: src/event/SightMoveEvent.cpp src/event/SightMoveEvent.h \
		src/event/Event.h \
		src/Field.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/QObject \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobject.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qflags.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstring.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qchar.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qlist.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobject_impl.h \
		src/util/Array.h \
		src/util/Define.h \
		src/Sight.h \
		/opt/Qt/5.3/gcc_64/include/QtOpenGL/QGLWidget \
		/opt/Qt/5.3/gcc_64/include/QtOpenGL/qgl.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qopengl.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qt_windows.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qopengles2ext.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qopenglext.h \
		/opt/Qt/5.3/gcc_64/include/QtWidgets/qwidget.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qrect.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsize.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpalette.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qpair.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qvector.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qregion.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qline.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qimage.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qhash.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qfont.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt/5.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qkeysequence.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qevent.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmap.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qset.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qurl.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qfile.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpaintengine.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpainter.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qtextoption.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/qpen.h \
		/opt/Qt/5.3/gcc_64/include/QtOpenGL/qglcolormap.h \
		/opt/Qt/5.3/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/opt/Qt/5.3/gcc_64/include/QtGui/QSurfaceFormat \
		/opt/Qt/5.3/gcc_64/include/QtGui/qsurfaceformat.h \
		src/util/Vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/SightMoveEvent.o src/event/SightMoveEvent.cpp

generated/Force.o: src/force/Force.cpp src/force/Force.h \
		src/util/Vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/Force.o src/force/Force.cpp

generated/Gravity.o: src/force/Gravity.cpp src/force/Gravity.h \
		src/force/Force.h \
		src/util/Vector.h \
		src/object/Object.h \
		src/util/Define.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/Gravity.o src/force/Gravity.cpp

generated/Impulse.o: src/force/Impulse.cpp src/force/Impulse.h \
		src/force/Force.h \
		src/util/Vector.h \
		src/object/Object.h \
		src/object/ObjectStatus.h \
		src/util/Array.h \
		src/util/Define.h \
		src/util/Calculater.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/Impulse.o src/force/Impulse.cpp

generated/StickForce.o: src/force/StickForce.cpp src/force/StickForce.h \
		src/force/Force.h \
		src/util/Vector.h \
		src/CrashResult.h \
		src/event/CrashEvent.h \
		src/event/Event.h \
		src/Field.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/QObject \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobject.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qflags.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstring.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qchar.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qlist.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt/5.3/gcc_64/include/QtCore/qobject_impl.h \
		src/util/Array.h \
		src/util/Define.h \
		src/object/Object.h \
		src/object/ObjectStatus.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/StickForce.o src/force/StickForce.cpp

generated/Gunner.o: src/object/Gunner.cpp src/object/Gunner.h \
		src/object/Player.h \
		src/object/Object.h \
		src/util/Vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/Gunner.o src/object/Gunner.cpp

generated/NumberBox.o: src/object/NumberBox.cpp src/object/NumberBox.h \
		src/object/Object.h \
		src/util/Vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/NumberBox.o src/object/NumberBox.cpp

generated/Object.o: src/object/Object.cpp src/object/Object.h \
		src/util/Vector.h \
		src/object/ObjectStatus.h \
		src/util/Array.h \
		src/util/Define.h \
		src/util/Calculater.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/Object.o src/object/Object.cpp

generated/ObjectStatus.o: src/object/ObjectStatus.cpp src/object/ObjectStatus.h \
		src/util/Array.h \
		src/util/Define.h \
		src/object/Object.h \
		src/util/Vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/ObjectStatus.o src/object/ObjectStatus.cpp

generated/Player.o: src/object/Player.cpp src/object/Player.h \
		src/object/Object.h \
		src/util/Vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/Player.o src/object/Player.cpp

generated/Calculater.o: src/util/Calculater.cpp src/util/Calculater.h \
		src/util/Vector.h \
		src/util/Define.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/Calculater.o src/util/Calculater.cpp

generated/Vector.o: src/util/Vector.cpp src/util/Vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/Vector.o src/util/Vector.cpp

generated/moc_Field.o: generated/moc_Field.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_Field.o generated/moc_Field.cpp

generated/moc_Sight.o: generated/moc_Sight.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generated/moc_Sight.o generated/moc_Sight.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

